//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daemon.WS_CreateJob {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_CreateJob.IService_CreateJob")]
    public interface IService_CreateJob {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CreateJob/SetDataJob", ReplyAction="http://tempuri.org/IService_CreateJob/SetDataJobResponse")]
        bool SetDataJob(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_CreateJob/SetDataJob", ReplyAction="http://tempuri.org/IService_CreateJob/SetDataJobResponse")]
        System.Threading.Tasks.Task<bool> SetDataJobAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_CreateJobChannel : Daemon.WS_CreateJob.IService_CreateJob, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_CreateJobClient : System.ServiceModel.ClientBase<Daemon.WS_CreateJob.IService_CreateJob>, Daemon.WS_CreateJob.IService_CreateJob {
        
        public Service_CreateJobClient() {
        }
        
        public Service_CreateJobClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_CreateJobClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CreateJobClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CreateJobClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SetDataJob(string xml) {
            return base.Channel.SetDataJob(xml);
        }
        
        public System.Threading.Tasks.Task<bool> SetDataJobAsync(string xml) {
            return base.Channel.SetDataJobAsync(xml);
        }
    }
}
