//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36415
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_CreateJob.Datos.DAO.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS_CreateJob.Datos.DAO.Recursos.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt.
        /// </summary>
        internal static string SQL_Attempt {
            get {
                return ResourceManager.GetString("SQL_Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string SQL_Date {
            get {
                return ResourceManager.GetString("SQL_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobDesc.
        /// </summary>
        internal static string SQL_Description {
            get {
                return ResourceManager.GetString("SQL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string SQL_Document {
            get {
                return ResourceManager.GetString("SQL_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMM_SP_INSERT_JOB.
        /// </summary>
        internal static string SQL_INSERT_JOB {
            get {
                return ResourceManager.GetString("SQL_INSERT_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxAttempt.
        /// </summary>
        internal static string SQL_MaxAttempt {
            get {
                return ResourceManager.GetString("SQL_MaxAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdStatus.
        /// </summary>
        internal static string SQL_Status {
            get {
                return ResourceManager.GetString("SQL_Status", resourceCulture);
            }
        }
    }
}
